uavorg/uavstack

com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.apm.js
com.creditease.uav.hook.dubbo/src/main/java/com/creditease/uav/hook/dubbo/DubboHookProxy.java
com.creditease.uav.hook.dubbo/src/main/java/com/creditease/uav/hook/dubbo/interceptors/DubboIT.java
com.creditease.uav.hook.dubbo/src/main/java/com/creditease/uav/hook/dubbo/invokeChain/DubboConsumerAdapter.java
com.creditease.uav.hook.dubbo/src/main/java/com/creditease/uav/hook/dubbo/invokeChain/DubboProviderAdapter.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/collect/SlowOperDataCollectHandler.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/collect/actions/SlowOperMethodAction.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/data/Span.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/http/SlowOperQueryHandler.java
com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/span/Span.java
com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/slowoper/handlers/MethodSlowOperHandler.java
com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/slowoper/spi/SlowOperConstants.java
com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/supporters/SlowOperSupporter.java
com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/TestRestService.java
com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/dubbo/IMyDubboService.java
com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/dubbo/MyDubboService.java

1，通过添加dubbo（Result）劫持点，捕获dubbo远程调用的返回数据和异常
1）对应IT位置增添Result参数；
2）添加获取Result中异常处理（以原异常为主，Result异常只有在原异常为null才记录）。
2，添加对应dubbo的adapter
1）虽然dubbo属于rpc，但其使用方式与method相同，故当前采用UAV的method协议方式记录。
3，HM中添加对应处理逻辑；
4，HM中添加对应查询逻辑；
5，前端展示添加对于dubbo的支持；

add invoke chain enhancement：dubbo full payload refinement

---

com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/healthmanager/messaging/handlers/ProfileDataMessageHandler.java

问题描述：
dubbo provider画像数据ip错误。
问题原因：
由于dubbo provider画像数据url拼接在HM端进行。HM端在拼接时误将本地ip拼接进去导致。这个出现在opensource版本中，we should keep on track.
bug修复：
从MA上送的画像数据中提取ip拼接。

fix dubbo provider ip bug

---

com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/adaptors/TomcatAdaptor.java
com.creditease.uav.tomcat.plus.core/src/main/java/com/creditease/tomcat/plus/interceptor/TomcatPlusIT.java

https://github.com/uavorg/uavstack/issues/31
fix 结果：
TomcatPlusIT.java onDeployUAVApp 方法中
tomcat7.0.30（不包含）小版本以下版本（到tomcat7.0.10）都统一和tomcat6进行一样的逻辑处理

Tomcat 7.0.0~7.0.23 has no getStartStopExecutor method

---

com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/hbagent/handlers/HBClientDefaultHandler.java
com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/procdetectagent/OSProcessScanner.java
com.creditease.uav.console/src/main/webapp/uavapp_godeye/uavnetwork/js/uav.network.js
com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/osproc/OSProcess.java

https://github.com/uavorg/uavstack/issues/41
1.Fix Issues #41 the MSCP node has no version information after the
upgrade.
2.Changed the default name of OSProcess from "UNKOWN" to "UNKNOWN".
3.Filter the empty disk information.

Fix Issues #41 the MSCP node has no version information after the upgrade

---

com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/UAVMetaDataMgr.java

https://github.com/uavorg/uavstack/issues/51
The system variables in "system.cache" can not be used when MSCP reboot
MSCP重启后无法正确使用system.cache的系统变量

The system variables in "system.cache" can not be used when MSCP reboot

---

com.creditease.uav.console/src/main/java/com/creditease/uav/apphub/filter/SessionAsyncFilter.java
com.creditease.uav.console/src/main/java/com/creditease/uav/apphub/rest/GUIService.java
com.creditease.uav.console/src/main/webapp/apphub/js/common/helper.js

----Apphub user behavior record add info---
我们需要一份匹配用户信息，在Apphub授权的邮箱组列表
1、在用户登录授权时：丰富用户session字段\内容：用户匹配的被授权的邮箱组和系统列表
2、用户行为日志（ulog）丰富字段、JS用户变量（前端同样可以获取登录用户数据）丰富字段
----- fix Apphub ajax assembly params not default----
1、apphub ajax contentType 添加默认类型：application/json; charset=UTF-8
2、原因描述：开启重调用链后，mof会对rs接口进行拦截处理，对没有定义上传参数的ajax提交请求，会使用默认处理。从而导致与rs接口不匹配，最终报错。

Apphub user behavior record add info & fix Apphub ajax assembly params not default

---

com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.appstream.js
com.creditease.uav.tomcat.plus.core/src/main/java/com/creditease/tomcat/plus/interceptor/TomcatPlusIT.java

https://github.com/uavorg/uavstack/issues/116
judge if args is undefine when call function onAppClientUpdate
https://github.com/uavorg/uavstack/issues/117
after tomcat8, tomcat use ParallelWebappClassLoader as it's webappclassloader, both of them are extends WebappClassLoaderBase. So change the classFilter from WebappClassLoader to WebappClassLoaderBase when class WebappClassLoaderBase exists(before tomcat7.0.64, WebappClassLoaderBase doesn't exist)

fix appstream.js  and jdbc hook bug

---

com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.apm.js

https://github.com/uavorg/uavstack/issues/122
在webapps下 如果应用名即为ROOT.war,找不到对应的url;不需要再加ROOT

When the application is named ROOT, the corresponding URL cannot be found and the log cannot be linked 

---

com.creditease.uav.hook.httpclients/src/main/java/com/creditease/uav/hook/httpclients3/sync/HttpClient3HookProxy.java
com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/adaptors/SpringBootTomcatAdaptor.java
com.creditease.uav.monitorframework.springbootFat/src/main/resources/application.properties
com.creditease.uav.tomcat.plus.core/src/main/java/com/creditease/tomcat/plus/interceptor/SpringBootTomcatPlusIT.java

Issue#134 
1.modify springboot appname's profiling，prefer configuration 'spring.application.name' rather than 'server.display-name'.
2.fix duplicate define class error when springboot config contextpath as '/'.

modify springboot appname's profiling&&fix duplicate define class error when springboot start 

---

com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/RuleFilterFactory.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/NodeInfoWatcher.java

1.日志画像中画像的路径存在多余'/'时，无法匹配正确的日志过滤规则。
例如：日志画像为/app/apollo/tomcat/logs//service/apollo-service-2017-12-26.log，但匹配时所用的key为/app/apollo/tomcat/logs/service/apollo-service-2017-12-26.log。
修改：过滤日志规则中多余的'/'等，使二者匹配。
2.container的采集的端口形式为ip:port，不是通常的port，在将其转为number时异常。
修改：用":" split后取port，过滤随机端口时用port，拼接key时用ip:port

Fix Log profile with redundant ‘/’ caused logs can‘t be collected && Type conversion error when the form of Container port is ip:port 

---

com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/RuntimeHelper.java

#153 
现象:在一个Windows 2003
Server环境中，当安装了MA并使用MA中的start.bat启动之后发现连接数和服务进程可以正常显示，但监控代理程序中的CPU使用率、内存使用率等进程性能指标无法正常采集；在运行一段时间之后发现连接数和服务进程都无法正常显示了，此时观察系统发现系统异常卡顿，甚至无法正常启动其他程序；打开任务管理器之后发现内存使用率飙高，后台启动了大量的cmd.exe与wmic.exe无法关闭，并且cmd.exe与wmic.exe的数量越来越多。
原因：原因是RuntimeHelper的RunTimeTask对Runtime.getRuntime().exec存在漏洞，在Linux和Win
7/10等系统中系统层面标准输入设备会自动关闭，而在win2003 server上不会。 
代码 Process ps = Runtime.getRuntime().exec(...) 每个process有3个标准输入/输出设备， 
•ps.getInputStream() 标准输出 
•ps.getErrorStream() 标准错误输出
•ps.getOutputStream 标准输入
ps.getOutputStream没有关闭导致wmic被hang住
修复方式：增加语句ps.getOutputStream().close();关闭标准输入设备

FIX at Windows 2003 Server cmd.exe and wmic.exe which generated by UAVStack uavagent running can not be automatically closed

---

com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/util/MonitorServerUtil.java

https://github.com/uavorg/uavstack/issues/151
修复如果basePath最后一位为/，获取的appid为空问题

Appid is ‘’ if the last character of basePath is ‘/’

---

com.creditease.uav.healthmanager.buildComponent/bin/run.sh
com.creditease.uav.healthmanager.buildComponent/config/agent.properties
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/AppHubManager.java

#335 
在apphubManager多线程处理大量http请求时，
1.增加线程拒绝策略，
2.同时加大队列大小，
3.启动时设置请求和相应超时时间，
增强代码在处理大量http请求时的健壮性.

The memory leak problem of apphubManager

---

com.creditease.uav.hook.mq/src/main/java/com/creditease/uav/hook/rabbitmq/interceptors/RabbitmqIT.java
com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/jee/JEEServiceRunGlobalFilterHandler.java
com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/slowoper/adapter/ServerSpanAdapter.java

#359 #360 
说明:
1,tomcat6.0.4系列使用servlet2.5的api,其中response接口中没有getStatus和getHeader方法,会导致异常.
2,rabbitmq调用链在produce未安装uav时,此处的mqheader中不含有span的信息,但是该请求的url是存在的,应该在if外进行记录
enhance :
1,从tomcat返回的reponsefacade中获取其持有的response对象,该对象含有getstatus和getHeader方法,同时对于开启重调用链对response加的壳进行脱壳处理.
2,将url移动到span是否存在判断的if语句外面进行获取

invokechain enhancement for rabbitmq and low version tomcat

---

com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ClientProfileHandler.java
com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/util/MonitorServerUtil.java
com.creditease.uav.tomcat.plus.core/src/main/java/com/creditease/tomcat/plus/interceptor/SpringBootTomcatPlusIT.java

https://github.com/uavorg/uavstack/issues/356
fix bug in ClientProfileHandler.class, the bug caused by special char in URL string, when parse the string into a URI Object, java.net.URL class will devide string into several parts and analysis each substring. when special character appears in "hostname" part of one URI string, it makes a URISyntaxException and an analyse fault. When we call function "getHost()",it returns null.

fix URI has "null" substring bug and remove excrescent path in appid

---

com.creditease.uav.hook.httpclients/src/main/java/com/creditease/uav/hook/httpclients/async/interceptors/ApacheAsyncHttpClientIT.java
com.creditease.uav.hook.httpclients/src/main/java/com/creditease/uav/hook/httpclients/sync/interceptors/ApacheHttpClientIT.java
com.creditease.uav.hook.httpclients/src/main/java/com/creditease/uav/hook/httpclients3/sync/interceptors/ApacheHttpClient3IT.java

http请求中HttpRequest中可能不包含ip:port导致httpclient画像没有http://ip:port，
如拿到的url不含"http"则获取HttpHost与其拼接

FIX HttpRequest does'nt contain ip:port causing httpclient profile without http://ip:port 

---

com.creditease.uav.console/src/main/webapp/uavapp_godfilter/groupfilter/js/groupfilter.js

https://github.com/uavorg/uavstack/issues/369
Apphub 服务治理--监控授权：
UAV应用下线后，在UAV容器监控中，定义的AppGroup（JAppGroup）将会不存在，
此时授权编辑时，将已经不存在的AppGroup屏蔽显示，
当用户页面提交的时候，自然不会有该数据提交，达到对授权信息删除垃圾数据的效果
代码补充

Apphub Authorized user experience enhancement 

---

com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/TaildirLogComponent.java
com.creditease.uav.base/src/main/java/com/creditease/agent/spi/IForkjoinWorker.java
com.creditease.uav.base/src/main/java/com/creditease/agent/workqueue/SystemForkjoinWorker.java
com.creditease.uav.collect/src/main/java/com/creditease/uav/collect/client/copylogagent/CopyOfProcessOfLogagent.java

https://github.com/uavorg/uavstack/issues/387
当前SystemForkjoinWorker对ForkJoinPool的封装限制太死，使用起来很不方便，修改如下：
1.增加提交task进ForkJoinPool的方法，支持所有类型的提交，包括Runnable、Callable、ForkJoinTask
2.增加getter返回类型
3.修改原LogAgent中使用的SystemForkjoinWorker的方法

Base component SystemForkjoinWorker modification

---

com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/adaptors/SpringBootTomcatAdaptor.java
com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/jee/servlet30/DynamicServletContextProcessor.java
com.creditease.uav.tomcat.plus.core/src/main/java/com/creditease/tomcat/plus/interceptor/SpringBootTomcatPlusIT.java

#394  #395 
issue：
1.重复注册filter和servlet导致NPE问题
2.springboot2.0.0以后设置contextpath的key从server.context-path变成server.servlet.context-path,导致获取的contextpath与hook时的contextPath不一致导致异常
fix：
1.增加判空条件
2.在启动过程中获取springboot的版本进行相应的适配

fix NPE problems caused by repeated registration of filters and servlets &&  adapt the context path configuration in springboot 2+

---

com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/handlers/ClientSpanInvokeChainHandler.java

#352 
threadName可以不唯一依然会导致生成的key值相同,这里修改为threadId.

Fix invokechain NPE problem

---

com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.apm.js
com.creditease.uav.elasticsearch.client/src/main/java/com/creditease/uav/elasticsearch/index/ESIndexHelper.java
com.creditease.uav.elasticsearch.client/src/test/java/com/creditease/uav/elasticsearch/client/DoTestESIndex.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/healthmanager/newlog/HMNewLogIndexMgr.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/healthmanager/newlog/handlers/NewLogDataMessageHandler.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/healthmanager/newlog/http/NewLogQueryHandler.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/InvokeChainIndexMgr.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/SlowOperIndexMgr.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/collect/SlowOperDataCollectHandler.java
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/http/SlowOperQueryHandler.java
com.creditease.uav.threadanalysis/src/main/java/com/creditease/uav/threadanalysis/server/ThreadAnalysisIndexMgr.java

1.日志、调用链、重调用链、线程分析分别用一个索引，由按周改为按天滚动。
2.日志索引的分片由2改为5，所有索引(日志、APM)的副本由0改为1。
3.索引改为按天滚动后之前24小时内的查询涉及两个索引，故改为当天查询。
4.日志、重调用链原索引与appid有关，修改后插入和查询时增加appid，且appid的type设为keyword
具体索引修改如下：
1）日志
原索引：applog_appid_yyyy-MM-dd，现索引：uav_applog_yyyy-MM-dd
原索引与appid有关，查询时使用appid和type，为区分不同应用，插入和查询ES时增加appid，且appid的type设为keyword
2）调用链
原索引：uav_ivc_db_yyyy-MM-dd，现索引：uav_ivc_yyyy-MM-dd
查询使用appuuid
3）重调用链
原索引：ivcdat_appid_yyyy-MM-dd，现索引：uav_ivcdat_yyyy-MM-dd
原索引与appid相关，查询使用appid和tranceid，重调用链数据中已经包含appid，故appid设为keyword
4）线程分析
原索引：uav_jta_db_yyyy-MM-dd，现索引：uav_jta_yyyy-MM-dd

Modify log and APM ES Index

---

com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/RewriteIvcOutputStream.java

RewriteIvcOutputStream类判断remainderLength错误
