uavorg/uavstack

com.creditease.uav.agent.buildComponent/pom.xml
com.creditease.uav.agent/pom.xml

agent's bulid remove threadanalysis's  redundant jars，only reserve threadanalysis client jar

agent's bulid remove threadanalysis's  redundant jars，only reserve threadanalysis client jar

---

com.creditease.uav.agent.buildComponent/config/ma_pro.properties
com.creditease.uav.agent.buildComponent/pom.xml
com.creditease.uav.collect/src/main/java/com/creditease/uav/collect/client/copylogagent/TailFileTaskJob.java
com.creditease.uav.collect/src/main/java/com/creditease/uav/collect/client/copylogagent/TailFilesMutiJobs.java
com.creditease.uav.healthmanager.buildComponent/bin/run.sh
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/StrategyJudgement.java
com.creditease.uav.monitorframework.buildComponent/config/uav.properties

fix ma_pro config jta enable true
fix monitor agent pom.xml to copy jta jar only
fix jta collect task NPE
fix RuntimeNotify description miss current value
fix monitorframework config NetCardIndex default 0

FIX JTA collect task NPE & build pom.xml 

---

.gitignore
com.creditease.uav.tomcat.plus.core/src/main/java/com/creditease/tomcat/plus/interceptor/SpringBootTomcatPlusIT.java

when springboot stops, sometimes there is an NPE. however, it doesn't matter. we fix this for better stopping.

SpringBootTomcatPlusIT onAppStop NPE

---

com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/hbagent/handlers/HBClientDefaultHandler.java
com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/osproc/DiskIOCollector.java
com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/osproc/ProcDiskIOCollector.java

https://github.com/uavorg/uavstack/issues/34
supported disk IO for Windows (win7 through 10), disk IO for each service process.

Add the ability to monitor Windows disk IO

---

com.creditease.uav.loghook/src/main/java/com/creditease/uav/log/hook/Log4jHookProxy.java
com.creditease.uav.loghook/src/main/java/com/creditease/uav/log/hook/LogBackHookProxy.java

https://github.com/uavorg/uavstack/issues/84
修复当开启日志追踪时，springboot启动异常。

fix springboot startup with exception when logtraceSupporter is started

---

README.md

https://github.com/uavorg/uavstack/issues/105
Change the urls to new downloading sites

Change the url for downloading

---

README.md

https://github.com/uavorg/uavstack/issues/105

Change maven repo url

---

com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.add.js
com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.win.js
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/NodeInfoWatcher.java

https://github.com/uavorg/uavstack/issues/100
1.降低进程死亡误报率
2.增加进程死亡预警配置支持

process death alarm enhanced && configuration support

---

com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/TaildirLogComponent.java

add "try finally {clear}" in closeTailFiles, prevent memory leakage by
clearing the "idleInodes" in finally.

Log collection error

---

com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/IPLinkProfileHandler.java

https://github.com/uavorg/uavstack/issues/129

 fix IPLinkProfile NPE when url contain special character

---

com.creditease.uav.agent.heartbeat/.gitignore
com.creditease.uav.console/src/main/webapp/apphub/css/comp.tablist.css
com.creditease.uav.console/src/main/webapp/apphub/js/common/tablist.js
com.creditease.uav.hook.redis/pom.xml

Show Instance Number on AppGroup for Application/System Monitor

Show Instance Number on AppGroup for Application/System Monitor

---

com.creditease.uav.threadanalysis/src/main/java/com/creditease/uav/threadanalysis/http/ThreadAnalysisQueryHandler.java

Set ES aggregation default count from 10 up to 1000.

Fixed Issue 149

---

com.creditease.uav.console/src/main/java/com/creditease/uav/godeye/rest/GodEyeRestService.java
com.creditease.uav.dbaccess/src/main/java/com/creditease/uav/datastore/core/OpentsdbDataStore.java
com.creditease.uav.healthmanager.buildComponent/config/hm_pro_apphubmgr.properties
com.creditease.uav.healthmanager.buildComponent/config/hm_pro_moserver.properties
com.creditease.uav.healthmanager.buildComponent/config/hm_pro_nodeserver.properties

https://github.com/uavorg/uavstack/issues/173
openTsdb optimization:
1.modify query openTsdb error process;
2.modify configuration file parameters.

openTsdb optimization

---

com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ComponentProfileHandler.java

https://github.com/uavorg/uavstack/issues/171

enhancement struts2 profire for struts.action.extension

---

com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/nodeopagent/actions/MOFCtrlAction.java
com.creditease.uav.healthmanager.buildComponent/config/agent.properties
com.creditease.uav.healthmanager.buildComponent/config/hm_pro_logserver.properties
com.creditease.uav.healthmanager.buildComponent/config/hm_pro_pfntfyserver.properties
com.creditease.uav.healthmanager.buildComponent/config/hm_test_logserver.properties
com.creditease.uav.healthmanager.buildComponent/config/hm_test_moserver.properties
com.creditease.uav.healthmanager.buildComponent/config/hm_test_nodeserver.properties
com.creditease.uav.healthmanager.buildComponent/config/hm_test_pnhbserver.properties
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/HealthManager.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/healthmanager/datastore/adaptors/NotifyDataAdpater.java

https://github.com/uavorg/uavstack/issues/176
openTsdb Configuration modification
modify hm_test configuration file parameters;
modify NodeInfoDataAdapter bug;
https://github.com/uavorg/uavstack/issues/178
mofCtrlAction optimization:
The judgment and processing of the return state code in the completed method;
notifyAdaptor optimization:
NotifyDataAdpater add notifyType column;

openTsdb Configuration modification

---

com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/JVMContainerOSDetector.java

https://github.com/uavorg/uavstack/issues/190

MonitorAgent detector.container.ports support ip:port

---

com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.apm.js
com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/http/SlowOperQueryHandler.java

issue #189
support rocketmq invoke chain

support rocketmq invoke chain

---

com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/listeners/InvokeChainClsInjectListener.java

method invoke chain support for springboot

---

com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/procdetectagent/NetworkIoDetector.java

Under the Windows system, MA runs for a long time, and the traffic collection opens the network card device too much.

---

com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ComponentProfileHandler.java

https://github.com/uavorg/uavstack/issues/214

struts2 profile enhancement

---

com.creditease.uav.agent.buildComponent/config/ma_pro.properties
com.creditease.uav.agent.buildComponent/config/ma_test.properties
com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/BaseDetector.java
com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/DetectorManager.java
com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/JVMToolHelper.java
com.creditease.uav.monitorframework.buildComponent/config/uav.properties
com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/datastore/DataObserver.java

1.change MOF's default datastore mode to http
2.mscp default use jmx datastore mode
3.http detector and jmx detector share a same detect worker pool

fix issues when enable both http&&jmx detect

---

com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/procwatch/ProcWatcher.java
com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/css/uav.notifystgy.css
com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.add.js
com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.win.js
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/NotifyStrategy.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/NodeInfoWatcher.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyCommonTask.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyTask.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyTimerTask.java
com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/NotificationCenter.java
com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/NCConstant.java
com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/NCEventStatusManager.java
com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/handlers/NCJudgementHandler.java
com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/task/PersistentTask.java

新增梯度报警收敛，支持自定义报警次数触发报警动作，优先级高于默认收敛规则,与默认报警收敛组成“双报警收敛”

Increase gradient alarm convergence

---

com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/JVMContainerOSDetector.java

add leave out code

---

com.creditease.uav.agent.buildComponent/config/agent.properties
com.creditease.uav.agent.buildComponent/config/ma_pro.properties
com.creditease.uav.agent.buildComponent/config/ma_test.properties
com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/LogAgent.java
com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/ReliableTaildirEventReader.java
com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/TailFileTaskJob.java
com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/TaildirLogComponent.java
com.creditease.uav.collect/src/main/java/com/creditease/uav/collect/client/copylogagent/ReliableTaildirEventReader.java

logagent optimization：
1.Increase the log output level
2.tailFiles and maybeReloadMap remove invalid inode nodes in logagent

logagent optimization

---

README.md
Readme-EN

Please review the English version for UAVStack Readme

UAVStack Readme-EN

---

com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.win.js
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/RuntimeNotifyCatcher.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/NotifyStrategy.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/StrategyJudgement.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/AbstractExprAdaptor.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/AppExprAdaptor.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/ClientExprAdaptor.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/HostExprAdaptor.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/JvmExprAdaptor.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/ProcExprAdaptor.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/ServerExprAdaptor.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/UrlExprAdaptor.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/TimerNotifyWorker.java
com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyTaskForTimer.java

time_based notification support notify cross diffirent metric type

time_based notification support notify cross diffirent metric type

---

com.creditease.uav.console/src/main/java/com/creditease/uav/godeye/rest/GodEyeRestService.java
com.creditease.uav.dbaccess/src/main/java/com/creditease/uav/datastore/core/MongoDBDataStore.java
com.creditease.uav.dbaccess/src/main/java/com/creditease/uav/datastore/mongo/MongodbImplStrategy.java
com.creditease.uav.healthmanager/src/test/java/testData/MongoDBQuery/DSfind.json

1.apphub查询逻辑修改，使用后端采用find查询，count计数
2.HM端对应逻辑完整化，find和count支持多个or以且（and）的形式存在
3.预警记录查询时改为latestrecord_ts（最近预警时间）排序，减少时间消耗并优化展示逻辑
4.DSfind.json示例修改

Alarm record query optimization

---

com.creditease.uav.base/src/main/java/com/creditease/agent/spi/ITimerWorkManager.java
com.creditease.uav.base/src/main/java/com/creditease/agent/workqueue/SystemScheduledWorkMgr.java
com.creditease.uav.base/src/main/java/com/creditease/agent/workqueue/SystemTimerWorkMgr.java

A regular task worker component based on ScheduledThreadPoolExecutor is added in package uav.base.
At the same time, the no use functions in interface ITimerWorkManager are deleted.

Add a regular task worker component based on ScheduledThreadPoolExecutor, and delete no use fun in the interface and its implements

---

com.creditease.uav.cache.redis/src/main/java/com/creditease/uav/cache/redis/AredisAsyncService.java

https://github.com/uavorg/uavstack/issues/374
AredisAsyncService Log Printing Efficiency Optimization
redis 服务日志打印效率优化：优减log输出、避免极限情况下大数据日志打印而导致内存溢出

AredisAsyncService Log Printing Efficiency Optimization

---

com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/hbagent/handlers/HBClientDefaultHandler.java
com.creditease.uav.console/src/main/webapp/uavapp_godeye/uavnetwork/js/uav.network.js
com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/NetworkHelper.java
com.creditease.uav.helper/src/main/java/com/creditease/uav/helpers/network/HostNewworkInfo.java

including network card name, ip, subnet mask, and broadcast address

Monitor network card information

---

com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/datacatch/BaseHttpMonitorDataCatchWorker.java

Custom metrics display updates

---

com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/hbagent/handlers/HBClientDefaultHandler.java
com.creditease.uav.console/src/main/webapp/uavapp_godeye/uavnetwork/js/uav.network.js
com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/NetworkHelper.java
com.creditease.uav.helper/src/main/java/com/creditease/uav/helpers/network/HostNewworkInfo.java

https://github.com/uavorg/uavstack/issues/393
增加网卡mac信息的mac信息的采集和展示

Increase the network card mac address

---

com.creditease.uav.console/src/main/webapp/uavapp_godeye/timesandtable/js/uav.tstable.js

fix issue 404

---

com.creditease.uav.console/src/main/webapp/uavapp_godeye/timesandtable/js/uav.tstable.js

fix time sand table query is abnormal when there are two points at the same time

---

com.creditease.uav.base/src/main/java/com/creditease/agent/monitor/api/NotificationEvent.java
com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifymgr/css/uav.notifymgr.css
com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifymgr/js/notify.main.js

Notify messages are displayed in different level -- info, warn and critical. Different level use different background color. Old message are suit for this new page.

Add display level on notify manager page for different notify messages

---

com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/util/TransformWrapperUtil.java

Support for multiple casing functions of response

---

com.creditease.uav.base/src/main/java/com/creditease/agent/spi/AbstractBaseHttpServComponent.java
com.creditease.uav.base/src/main/java/com/creditease/agent/spi/AbstractHttpServiceComponent.java
com.creditease.uav.base/src/main/java/com/creditease/agent/spi/AbstractHttpServiceComponent2.java

https://github.com/uavorg/uavstack/issues/433
https://github.com/uavorg/uavstack/issues/434
When the port is already in use, MSCP should be exit.
MSCP http handler will return 404 when no matching handler can be acquired

MSCP enhancements

---

com.creditease.uav.loghook/src/main/java/com/creditease/uav/log/hook/Log4jHookProxy.java
com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/adaptors/SpringBootTomcatAdaptor.java

调用链日志关联支持log4j中的RollingFileAppender(以固定大小滚动日志)

logtrace support log4j RollingFileAppender

---

README.md
README中文版.md

https://github.com/uavorg/uavstack/issues/450

Delelte buildFat introduction in ReadMe

---

com.creditease.uav.base/src/main/java/com/creditease/agent/spi/AbstractHttpServiceComponent.java
com.creditease.uav.base/src/main/java/com/creditease/agent/spi/AbstractHttpServiceComponent2.java

If multi MA start in the same port, the failure MA will be exit

---

com.creditease.uav.console/src/main/webapp/apphub/js/common/helper.js

#460 
增加对数组中元素是否是对象的判断，如果是，继续递归拷贝，否则直接复制

Copy function bugFix in the helper.js

---

com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/JVMToolHelper.java

uavagent get JVM process fail

---

com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ComponentProfileHandler.java

https://github.com/uavorg/uavstack/issues/482

enhance struts2 profile
